# Generated by Django 4.0 on 2022-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.URLField(null=True),
        ),
    ]
