# Generated by Django 4.0 on 2022-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_recommended_rename_field_name_post_live_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recommend',
            field=models.ManyToManyField(to='home.Recommended'),
        ),
    ]
