# Generated by Django 4.0 on 2022-02-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
